### ISSUE TITLE
Stop Drew from ruining the fun

### ISSUE THREAD

**Issue by zieski** [neileon81/tilt-maze#1]
https://github.com/neileon81/tilt-maze/blob/d0bb4af264db2859a302d041b0acc3b30553c3d6/vendor/javascript/tilt_maze.js#L663

I didn't test it but I think if you replace the .every with:
```
      balls.reduce(
        (sum, ball) => distance2D(ball, { x: 350 / 2, y: 315 / 2 }) < 65 / 2 ? sum + 1 : sum, 0
      ) == 4
```
It will check that you have 4 balls in the circle instead of that every ball is in the circle.

**Comment by latortuga** [comment]
Resolved by a3796a6bd539fb8b2dd3dde1db29b2ae11c7b4f4
